name: Shops
version: ${project.version}
main: shops.Shops
api-version: 1.16
authors: [Blake, Jorge, Mason]
description: ShopPlugin
website: thealater.com
softdepend: [HolographicDisplays, GemsEconomy]
commands:
  shops:
    description: shops
  newshops:
      description: new shops