name: Shops
version: 0.9-SNAPSHOT
main: shops.Shops
api-version: 1.16
authors: [Blake, Jorge, Mason]
description: ShopPlugin
website: thealater.com
softdepend: [HolographicDisplays]
commands:
  shops:
    description: shops
    usage: /<command>
  newshops:
      description: new shops
      usage: /<command>